"""Smart CLI — project generator that scaffolds FastAPI projects.

Provides a Typer-based CLI with commands for initializing new FastAPI projects
with smart defaults and showing version information.
"""

from __future__ import annotations

from pathlib import Path

import typer

app = typer.Typer(
    name="smartvintaawesomekit",
    help="SmartVintaAwesomeKit — Create new FastAPI projects with smart defaults",
)


@app.callback()
def callback() -> None:
    """SmartVintaAwesomeKit CLI — Generate new projects or get help."""
    pass


@app.command()
def init(
    project_name: str = typer.Argument(..., help="Name of the project to create"),
    directory: str | None = typer.Option(
        None,
        "--directory",
        "-d",
        help="Parent directory for the project (default: current directory)",
    ),
    database: str = typer.Option(
        "sqlite",
        "--database",
        help="Default database type (sqlite, postgresql)",
    ),
) -> None:
    """Create a new FastAPI project with smart defaults.

    Generates a complete project directory with:
    - pyproject.toml with project metadata
    - app/main.py with FastAPI application
    - app/database.py with async SQLAlchemy setup
    - app/models/, app/schemas/, app/routes/
    - tests/ directory with sample tests
    - Dockerfile, Procfile, railway.json for deployment
    """
    base_dir = Path(directory) if directory and isinstance(directory, str) else Path.cwd()
    project_dir = base_dir / project_name
    project_dir.mkdir(parents=True, exist_ok=True)

    # Create package directories
    (project_dir / "app").mkdir(exist_ok=True)
    (project_dir / "app" / "models").mkdir(exist_ok=True)
    (project_dir / "app" / "schemas").mkdir(exist_ok=True)
    (project_dir / "app" / "routes").mkdir(exist_ok=True)
    (project_dir / "tests").mkdir(exist_ok=True)

    # Create __init__.py files
    for subdir in ["app", "app/models", "app/schemas", "app/routes", "tests"]:
        init_file = project_dir / subdir / "__init__.py"
        init_file.touch()

    # Create pyproject.toml
    pyproject_content = f'''[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{project_name}"
version = "0.1.0"
description = "A FastAPI project generated by smartvintaawesomekit"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.136.0",
    "uvicorn[standard]>=0.20.0",
    "sqlalchemy>=2.0",
    "pydantic>=2.0",
    "pydantic-settings>=2.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "pytest-asyncio>=0.23.0",
    "ruff>=0.3.0",
]

[project.scripts]
{project_name} = "app.main:app"
'''
    (project_dir / "pyproject.toml").write_text(pyproject_content)

    # Create app/main.py
    main_content = f'''"""Main FastAPI application for {project_name}."""

from fastapi import FastAPI

app = FastAPI(title="{project_name}")


@app.get("/")
async def root() -> dict[str, str]:
    """Health check endpoint."""
    return {{"message": "Hello from {project_name}"}}
'''
    (project_dir / "app" / "main.py").write_text(main_content)

    # Create app/database.py
    db_content = '''"""Database configuration and session management."""

from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine, async_sessionmaker

DATABASE_URL = "sqlite+aiosqlite:///./dev.db"

engine = create_async_engine(DATABASE_URL, echo=False)
async_session = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)


async def get_db():
    """Get a database session."""
    async with async_session() as session:
        yield session
'''
    (project_dir / "app" / "database.py").write_text(db_content)

    # Create Procfile
    (project_dir / "Procfile").write_text("web: uvicorn app.main:app --host 0.0.0.0 --port $PORT\n")

    # Create railway.json
    railway_content = '''{
  "$schema": "https://railway.app/railway.schema.json",
  "build": {
    "builder": "NIXPACKS"
  },
  "deploy": {
    "startCommand": "uvicorn app.main:app --host 0.0.0.0 --port $PORT",
    "healthcheckPath": "/"
  }
}
'''
    (project_dir / "railway.json").write_text(railway_content)

    # Create Dockerfile
    dockerfile_content = '''FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml .
RUN pip install --no-cache-dir .

COPY . .

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
'''
    (project_dir / "Dockerfile").write_text(dockerfile_content)

    # Create sample test
    test_content = f'''"""Sample tests for {project_name}."""

from fastapi.testclient import TestClient
from app.main import app

client = TestClient(app)


def test_root():
    """Test the root endpoint."""
    response = client.get("/")
    assert response.status_code == 200
    assert "message" in response.json()
'''
    (project_dir / "tests" / "test_main.py").write_text(test_content)

    typer.echo(f"✅ Created project '{project_name}' in {project_dir}")
    typer.echo(f"   Database: {database}")
    typer.echo("   Next steps:")
    typer.echo(f"   cd {project_name}")
    typer.echo("   pip install -e '.[dev]'")
    typer.echo("   pytest")


@app.command()
def version() -> None:
    """Show the installed version."""
    from smartvintaawesomekit import __version__

    typer.echo(f"smartvintaawesomekit v{__version__}")


__all__ = ["app"]
